export interface PhoneCountry {
  iso: string;
  name: string;
  flag: string;
  dialCode: string;
}

export const PHONE_COUNTRIES: PhoneCountry[] = [
  // Afrique de l'Ouest (priorité marché)
  { iso: 'GN', name: 'Guinée', flag: '🇬🇳', dialCode: '+224' },
  { iso: 'SN', name: 'Sénégal', flag: '🇸🇳', dialCode: '+221' },
  { iso: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', dialCode: '+225' },
  { iso: 'ML', name: 'Mali', flag: '🇲🇱', dialCode: '+223' },
  { iso: 'BF', name: 'Burkina Faso', flag: '🇧🇫', dialCode: '+226' },
  { iso: 'NE', name: 'Niger', flag: '🇳🇪', dialCode: '+227' },
  { iso: 'TG', name: 'Togo', flag: '🇹🇬', dialCode: '+228' },
  { iso: 'BJ', name: 'Bénin', flag: '🇧🇯', dialCode: '+229' },
  { iso: 'GW', name: 'Guinée-Bissau', flag: '🇬🇼', dialCode: '+245' },
  { iso: 'GM', name: 'Gambie', flag: '🇬🇲', dialCode: '+220' },
  { iso: 'SL', name: 'Sierra Leone', flag: '🇸🇱', dialCode: '+232' },
  { iso: 'LR', name: 'Liberia', flag: '🇱🇷', dialCode: '+231' },
  { iso: 'MR', name: 'Mauritanie', flag: '🇲🇷', dialCode: '+222' },
  { iso: 'CV', name: 'Cap-Vert', flag: '🇨🇻', dialCode: '+238' },
  { iso: 'GH', name: 'Ghana', flag: '🇬🇭', dialCode: '+233' },
  { iso: 'NG', name: 'Nigeria', flag: '🇳🇬', dialCode: '+234' },

  // Afrique centrale
  { iso: 'CM', name: 'Cameroun', flag: '🇨🇲', dialCode: '+237' },
  { iso: 'CD', name: 'RD Congo', flag: '🇨🇩', dialCode: '+243' },
  { iso: 'CG', name: 'Congo', flag: '🇨🇬', dialCode: '+242' },
  { iso: 'GA', name: 'Gabon', flag: '🇬🇦', dialCode: '+241' },
  { iso: 'TD', name: 'Tchad', flag: '🇹🇩', dialCode: '+235' },
  { iso: 'CF', name: 'République centrafricaine', flag: '🇨🇫', dialCode: '+236' },
  { iso: 'GQ', name: 'Guinée équatoriale', flag: '🇬🇶', dialCode: '+240' },
  { iso: 'ST', name: 'Sao Tomé-et-Principe', flag: '🇸🇹', dialCode: '+239' },
  { iso: 'AO', name: 'Angola', flag: '🇦🇴', dialCode: '+244' },

  // Afrique de l'Est
  { iso: 'KE', name: 'Kenya', flag: '🇰🇪', dialCode: '+254' },
  { iso: 'TZ', name: 'Tanzanie', flag: '🇹🇿', dialCode: '+255' },
  { iso: 'UG', name: 'Ouganda', flag: '🇺🇬', dialCode: '+256' },
  { iso: 'RW', name: 'Rwanda', flag: '🇷🇼', dialCode: '+250' },
  { iso: 'BI', name: 'Burundi', flag: '🇧🇮', dialCode: '+257' },
  { iso: 'ET', name: 'Éthiopie', flag: '🇪🇹', dialCode: '+251' },
  { iso: 'SO', name: 'Somalie', flag: '🇸🇴', dialCode: '+252' },
  { iso: 'DJ', name: 'Djibouti', flag: '🇩🇯', dialCode: '+253' },
  { iso: 'ER', name: 'Érythrée', flag: '🇪🇷', dialCode: '+291' },
  { iso: 'SS', name: 'Soudan du Sud', flag: '🇸🇸', dialCode: '+211' },
  { iso: 'SD', name: 'Soudan', flag: '🇸🇩', dialCode: '+249' },
  { iso: 'MZ', name: 'Mozambique', flag: '🇲🇿', dialCode: '+258' },
  { iso: 'MG', name: 'Madagascar', flag: '🇲🇬', dialCode: '+261' },
  { iso: 'MU', name: 'Maurice', flag: '🇲🇺', dialCode: '+230' },
  { iso: 'SC', name: 'Seychelles', flag: '🇸🇨', dialCode: '+248' },
  { iso: 'KM', name: 'Comores', flag: '🇰🇲', dialCode: '+269' },
  { iso: 'MW', name: 'Malawi', flag: '🇲🇼', dialCode: '+265' },
  { iso: 'ZM', name: 'Zambie', flag: '🇿🇲', dialCode: '+260' },

  // Afrique australe / du Nord
  { iso: 'ZA', name: 'Afrique du Sud', flag: '🇿🇦', dialCode: '+27' },
  { iso: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', dialCode: '+263' },
  { iso: 'NA', name: 'Namibie', flag: '🇳🇦', dialCode: '+264' },
  { iso: 'BW', name: 'Botswana', flag: '🇧🇼', dialCode: '+267' },
  { iso: 'LS', name: 'Lesotho', flag: '🇱🇸', dialCode: '+266' },
  { iso: 'SZ', name: 'Eswatini', flag: '🇸🇿', dialCode: '+268' },
  { iso: 'MA', name: 'Maroc', flag: '🇲🇦', dialCode: '+212' },
  { iso: 'DZ', name: 'Algérie', flag: '🇩🇿', dialCode: '+213' },
  { iso: 'TN', name: 'Tunisie', flag: '🇹🇳', dialCode: '+216' },
  { iso: 'LY', name: 'Libye', flag: '🇱🇾', dialCode: '+218' },
  { iso: 'EG', name: 'Égypte', flag: '🇪🇬', dialCode: '+20' },

  // Europe
  { iso: 'FR', name: 'France', flag: '🇫🇷', dialCode: '+33' },
  { iso: 'BE', name: 'Belgique', flag: '🇧🇪', dialCode: '+32' },
  { iso: 'CH', name: 'Suisse', flag: '🇨🇭', dialCode: '+41' },
  { iso: 'LU', name: 'Luxembourg', flag: '🇱🇺', dialCode: '+352' },
  { iso: 'DE', name: 'Allemagne', flag: '🇩🇪', dialCode: '+49' },
  { iso: 'GB', name: 'Royaume-Uni', flag: '🇬🇧', dialCode: '+44' },
  { iso: 'IE', name: 'Irlande', flag: '🇮🇪', dialCode: '+353' },
  { iso: 'ES', name: 'Espagne', flag: '🇪🇸', dialCode: '+34' },
  { iso: 'PT', name: 'Portugal', flag: '🇵🇹', dialCode: '+351' },
  { iso: 'IT', name: 'Italie', flag: '🇮🇹', dialCode: '+39' },
  { iso: 'NL', name: 'Pays-Bas', flag: '🇳🇱', dialCode: '+31' },
  { iso: 'AT', name: 'Autriche', flag: '🇦🇹', dialCode: '+43' },
  { iso: 'DK', name: 'Danemark', flag: '🇩🇰', dialCode: '+45' },
  { iso: 'SE', name: 'Suède', flag: '🇸🇪', dialCode: '+46' },
  { iso: 'NO', name: 'Norvège', flag: '🇳🇴', dialCode: '+47' },
  { iso: 'FI', name: 'Finlande', flag: '🇫🇮', dialCode: '+358' },
  { iso: 'IS', name: 'Islande', flag: '🇮🇸', dialCode: '+354' },
  { iso: 'PL', name: 'Pologne', flag: '🇵🇱', dialCode: '+48' },
  { iso: 'CZ', name: 'Tchéquie', flag: '🇨🇿', dialCode: '+420' },
  { iso: 'SK', name: 'Slovaquie', flag: '🇸🇰', dialCode: '+421' },
  { iso: 'HU', name: 'Hongrie', flag: '🇭🇺', dialCode: '+36' },
  { iso: 'RO', name: 'Roumanie', flag: '🇷🇴', dialCode: '+40' },
  { iso: 'BG', name: 'Bulgarie', flag: '🇧🇬', dialCode: '+359' },
  { iso: 'GR', name: 'Grèce', flag: '🇬🇷', dialCode: '+30' },
  { iso: 'HR', name: 'Croatie', flag: '🇭🇷', dialCode: '+385' },
  { iso: 'SI', name: 'Slovénie', flag: '🇸🇮', dialCode: '+386' },
  { iso: 'RS', name: 'Serbie', flag: '🇷🇸', dialCode: '+381' },
  { iso: 'BA', name: 'Bosnie-Herzégovine', flag: '🇧🇦', dialCode: '+387' },
  { iso: 'ME', name: 'Monténégro', flag: '🇲🇪', dialCode: '+382' },
  { iso: 'MK', name: 'Macédoine du Nord', flag: '🇲🇰', dialCode: '+389' },
  { iso: 'AL', name: 'Albanie', flag: '🇦🇱', dialCode: '+355' },
  { iso: 'XK', name: 'Kosovo', flag: '🇽🇰', dialCode: '+383' },
  { iso: 'LT', name: 'Lituanie', flag: '🇱🇹', dialCode: '+370' },
  { iso: 'LV', name: 'Lettonie', flag: '🇱🇻', dialCode: '+371' },
  { iso: 'EE', name: 'Estonie', flag: '🇪🇪', dialCode: '+372' },
  { iso: 'UA', name: 'Ukraine', flag: '🇺🇦', dialCode: '+380' },
  { iso: 'BY', name: 'Biélorussie', flag: '🇧🇾', dialCode: '+375' },
  { iso: 'MD', name: 'Moldavie', flag: '🇲🇩', dialCode: '+373' },
  { iso: 'RU', name: 'Russie', flag: '🇷🇺', dialCode: '+7' },
  { iso: 'MT', name: 'Malte', flag: '🇲🇹', dialCode: '+356' },
  { iso: 'CY', name: 'Chypre', flag: '🇨🇾', dialCode: '+357' },
  { iso: 'AD', name: 'Andorre', flag: '🇦🇩', dialCode: '+376' },
  { iso: 'MC', name: 'Monaco', flag: '🇲🇨', dialCode: '+377' },
  { iso: 'SM', name: 'Saint-Marin', flag: '🇸🇲', dialCode: '+378' },
  { iso: 'VA', name: 'Vatican', flag: '🇻🇦', dialCode: '+379' },
  { iso: 'LI', name: 'Liechtenstein', flag: '🇱🇮', dialCode: '+423' },

  // Amérique du Nord
  { iso: 'US', name: 'États-Unis', flag: '🇺🇸', dialCode: '+1' },
  { iso: 'CA', name: 'Canada', flag: '🇨🇦', dialCode: '+1' },
  { iso: 'MX', name: 'Mexique', flag: '🇲🇽', dialCode: '+52' },

  // Amérique centrale / Caraïbes
  { iso: 'GT', name: 'Guatemala', flag: '🇬🇹', dialCode: '+502' },
  { iso: 'BZ', name: 'Belize', flag: '🇧🇿', dialCode: '+501' },
  { iso: 'HN', name: 'Honduras', flag: '🇭🇳', dialCode: '+504' },
  { iso: 'SV', name: 'Salvador', flag: '🇸🇻', dialCode: '+503' },
  { iso: 'NI', name: 'Nicaragua', flag: '🇳🇮', dialCode: '+505' },
  { iso: 'CR', name: 'Costa Rica', flag: '🇨🇷', dialCode: '+506' },
  { iso: 'PA', name: 'Panama', flag: '🇵🇦', dialCode: '+507' },
  { iso: 'CU', name: 'Cuba', flag: '🇨🇺', dialCode: '+53' },
  { iso: 'HT', name: 'Haïti', flag: '🇭🇹', dialCode: '+509' },
  { iso: 'DO', name: 'République dominicaine', flag: '🇩🇴', dialCode: '+1' },
  { iso: 'JM', name: 'Jamaïque', flag: '🇯🇲', dialCode: '+1' },
  { iso: 'TT', name: 'Trinité-et-Tobago', flag: '🇹🇹', dialCode: '+1' },
  { iso: 'BB', name: 'Barbade', flag: '🇧🇧', dialCode: '+1' },
  { iso: 'BS', name: 'Bahamas', flag: '🇧🇸', dialCode: '+1' },
  { iso: 'GP', name: 'Guadeloupe', flag: '🇬🇵', dialCode: '+590' },
  { iso: 'MQ', name: 'Martinique', flag: '🇲🇶', dialCode: '+596' },

  // Amérique du Sud
  { iso: 'BR', name: 'Brésil', flag: '🇧🇷', dialCode: '+55' },
  { iso: 'AR', name: 'Argentine', flag: '🇦🇷', dialCode: '+54' },
  { iso: 'CL', name: 'Chili', flag: '🇨🇱', dialCode: '+56' },
  { iso: 'CO', name: 'Colombie', flag: '🇨🇴', dialCode: '+57' },
  { iso: 'PE', name: 'Pérou', flag: '🇵🇪', dialCode: '+51' },
  { iso: 'VE', name: 'Venezuela', flag: '🇻🇪', dialCode: '+58' },
  { iso: 'EC', name: 'Équateur', flag: '🇪🇨', dialCode: '+593' },
  { iso: 'BO', name: 'Bolivie', flag: '🇧🇴', dialCode: '+591' },
  { iso: 'PY', name: 'Paraguay', flag: '🇵🇾', dialCode: '+595' },
  { iso: 'UY', name: 'Uruguay', flag: '🇺🇾', dialCode: '+598' },
  { iso: 'GY', name: 'Guyana', flag: '🇬🇾', dialCode: '+592' },
  { iso: 'SR', name: 'Suriname', flag: '🇸🇷', dialCode: '+597' },
  { iso: 'GF', name: 'Guyane française', flag: '🇬🇫', dialCode: '+594' },

  // Moyen-Orient
  { iso: 'SA', name: 'Arabie saoudite', flag: '🇸🇦', dialCode: '+966' },
  { iso: 'AE', name: 'Émirats arabes unis', flag: '🇦🇪', dialCode: '+971' },
  { iso: 'QA', name: 'Qatar', flag: '🇶🇦', dialCode: '+974' },
  { iso: 'BH', name: 'Bahreïn', flag: '🇧🇭', dialCode: '+973' },
  { iso: 'KW', name: 'Koweït', flag: '🇰🇼', dialCode: '+965' },
  { iso: 'OM', name: 'Oman', flag: '🇴🇲', dialCode: '+968' },
  { iso: 'YE', name: 'Yémen', flag: '🇾🇪', dialCode: '+967' },
  { iso: 'JO', name: 'Jordanie', flag: '🇯🇴', dialCode: '+962' },
  { iso: 'LB', name: 'Liban', flag: '🇱🇧', dialCode: '+961' },
  { iso: 'SY', name: 'Syrie', flag: '🇸🇾', dialCode: '+963' },
  { iso: 'IQ', name: 'Irak', flag: '🇮🇶', dialCode: '+964' },
  { iso: 'IR', name: 'Iran', flag: '🇮🇷', dialCode: '+98' },
  { iso: 'IL', name: 'Israël', flag: '🇮🇱', dialCode: '+972' },
  { iso: 'PS', name: 'Palestine', flag: '🇵🇸', dialCode: '+970' },
  { iso: 'TR', name: 'Turquie', flag: '🇹🇷', dialCode: '+90' },

  // Asie centrale
  { iso: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', dialCode: '+7' },
  { iso: 'UZ', name: 'Ouzbékistan', flag: '🇺🇿', dialCode: '+998' },
  { iso: 'TM', name: 'Turkménistan', flag: '🇹🇲', dialCode: '+993' },
  { iso: 'TJ', name: 'Tadjikistan', flag: '🇹🇯', dialCode: '+992' },
  { iso: 'KG', name: 'Kirghizistan', flag: '🇰🇬', dialCode: '+996' },
  { iso: 'AF', name: 'Afghanistan', flag: '🇦🇫', dialCode: '+93' },
  { iso: 'AM', name: 'Arménie', flag: '🇦🇲', dialCode: '+374' },
  { iso: 'AZ', name: 'Azerbaïdjan', flag: '🇦🇿', dialCode: '+994' },
  { iso: 'GE', name: 'Géorgie', flag: '🇬🇪', dialCode: '+995' },

  // Asie du Sud
  { iso: 'IN', name: 'Inde', flag: '🇮🇳', dialCode: '+91' },
  { iso: 'PK', name: 'Pakistan', flag: '🇵🇰', dialCode: '+92' },
  { iso: 'BD', name: 'Bangladesh', flag: '🇧🇩', dialCode: '+880' },
  { iso: 'LK', name: 'Sri Lanka', flag: '🇱🇰', dialCode: '+94' },
  { iso: 'NP', name: 'Népal', flag: '🇳🇵', dialCode: '+977' },
  { iso: 'BT', name: 'Bhoutan', flag: '🇧🇹', dialCode: '+975' },
  { iso: 'MV', name: 'Maldives', flag: '🇲🇻', dialCode: '+960' },

  // Asie de l'Est
  { iso: 'CN', name: 'Chine', flag: '🇨🇳', dialCode: '+86' },
  { iso: 'JP', name: 'Japon', flag: '🇯🇵', dialCode: '+81' },
  { iso: 'KR', name: 'Corée du Sud', flag: '🇰🇷', dialCode: '+82' },
  { iso: 'KP', name: 'Corée du Nord', flag: '🇰🇵', dialCode: '+850' },
  { iso: 'TW', name: 'Taïwan', flag: '🇹🇼', dialCode: '+886' },
  { iso: 'HK', name: 'Hong Kong', flag: '🇭🇰', dialCode: '+852' },
  { iso: 'MO', name: 'Macao', flag: '🇲🇴', dialCode: '+853' },
  { iso: 'MN', name: 'Mongolie', flag: '🇲🇳', dialCode: '+976' },

  // Asie du Sud-Est
  { iso: 'VN', name: 'Vietnam', flag: '🇻🇳', dialCode: '+84' },
  { iso: 'TH', name: 'Thaïlande', flag: '🇹🇭', dialCode: '+66' },
  { iso: 'MM', name: 'Birmanie', flag: '🇲🇲', dialCode: '+95' },
  { iso: 'KH', name: 'Cambodge', flag: '🇰🇭', dialCode: '+855' },
  { iso: 'LA', name: 'Laos', flag: '🇱🇦', dialCode: '+856' },
  { iso: 'MY', name: 'Malaisie', flag: '🇲🇾', dialCode: '+60' },
  { iso: 'SG', name: 'Singapour', flag: '🇸🇬', dialCode: '+65' },
  { iso: 'ID', name: 'Indonésie', flag: '🇮🇩', dialCode: '+62' },
  { iso: 'PH', name: 'Philippines', flag: '🇵🇭', dialCode: '+63' },
  { iso: 'BN', name: 'Brunei', flag: '🇧🇳', dialCode: '+673' },
  { iso: 'TL', name: 'Timor oriental', flag: '🇹🇱', dialCode: '+670' },

  // Océanie
  { iso: 'AU', name: 'Australie', flag: '🇦🇺', dialCode: '+61' },
  { iso: 'NZ', name: 'Nouvelle-Zélande', flag: '🇳🇿', dialCode: '+64' },
  { iso: 'FJ', name: 'Fidji', flag: '🇫🇯', dialCode: '+679' },
  { iso: 'PG', name: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬', dialCode: '+675' },
  { iso: 'NC', name: 'Nouvelle-Calédonie', flag: '🇳🇨', dialCode: '+687' },
  { iso: 'PF', name: 'Polynésie française', flag: '🇵🇫', dialCode: '+689' },
  { iso: 'WS', name: 'Samoa', flag: '🇼🇸', dialCode: '+685' },
  { iso: 'TO', name: 'Tonga', flag: '🇹🇴', dialCode: '+676' },
  { iso: 'VU', name: 'Vanuatu', flag: '🇻🇺', dialCode: '+678' },
  { iso: 'SB', name: 'Îles Salomon', flag: '🇸🇧', dialCode: '+677' }
];
